name: Flutter Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Data protection
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Generate translation packs
        run: flutter gen-l10n

      - name: Run formatter check
        run: dart format --set-exit-if-changed .

      - name: Run static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test
