name: Build and Release Android App

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Data protection
        run: flutter config --no-analytics

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Generate translation packs
        run: flutter gen-l10n

      - name: Set APK name
        id: vars
        run: |
          echo "APK_NAME=build/app/outputs/flutter-apk/ntunlock-$GITHUB_REF_NAME.apk" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT

      - name: Check APK name
        run: |
          echo ${{ steps.vars.outputs.APK_NAME }}

#      - name: Build APK for release
#        run: |
#          flutter build apk --release

#      - name: Rename APK
#        run: |
#          mv build/app/outputs/flutter-apk/app-release.apk ${{ steps.vars.outputs.APK_NAME }}

      - name: Create Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.vars.outputs.REF_NAME }}
          body_path: ReleaseNotes.md
#          files: ${{ steps.vars.outputs.APK_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}