name: Build and Release Android App

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Data protection
        run: flutter config --no-analytics

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Generate translation packs
        run: flutter gen-l10n

      - name: Build APK for release
        run: |
          flutter build apk --release

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/ntunlock-${GITHUB_REF##*/}.apk

      - name: Create Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-ReleaseNotes.md
          files: build/app/outputs/flutter-apk/ntunlock-${GITHUB_REF##*/}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}